### ISSUE TITLE
Invalid value: Only valid value is 0: 1

### ISSUE THREAD

**Issue by Jupi007** [xtyxtyx/unix_disk_space#2]
Hi,
First at all thanks for this library :)
I wanted to contribute by making it null safety compliant, so I tried to run the example file, but it returned this error:

```
Unhandled exception:
RangeError (index): Invalid value: Only valid value is 0: 1
#0      List.[] (dart:core-patch/growable_array.dart:254:60)
#1      parseOutput                package:unix_disk_space/src/unix_disk_space.dart:38
#2      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:183:26)
#3      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:198:26)
#4      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#5      new List.of (dart:core-patch/array_patch.dart:50:28)
#6      Iterable.toList (dart:core/iterable.dart:388:12)
#7      _run                package:unix_disk_space/src/unix_disk_space.dart:50
<asynchronous suspension>
#8      main                example/lib/main.dart:4
<asynchronous suspension>
```

I'm using Ubuntu 21.04 with `df` 8.32.

**Comment by Jupi007** [comment]
@xtyxtyx Any news on this?
